version: "3.9"

services:
  gitsync:
    image: robtec/git-sync:4
    container_name: gitsync
    environment:
      GITSYNC_REPO: https://github.com/kubernetes/git-sync
      GITSYNC_PERIOD: 30s
      GITSYNC_ROOT: /tmp/git/root
    volumes:
      - sync-dir:/tmp/git/root

volumes:
  sync-dir:
