version: "3.9"

services:
  gitsync:
    image: robtec/git-sync:4
    container_name: gitsync
    command:
      - |
        --repo=https://github.com/kubernetes/git-sync \
        --root=/tmp/git/root \
        --period=30s

    volumes:
      - sync-dir:/tmp/git/root

volumes:
  sync-db:
